bams: "example-configs/arg-nz-ca-chinook/config/bams.tsv"
pwcomps: "example-configs/arg-nz-ca-chinook/config/pwcomps.tsv"
genome: "example-configs/arg-nz-ca-chinook/data/GCF_018296145.1_Otsh_v2.0_genomic.fna"

modes: ["BY_CHROM"]
chroms: "example-configs/arg-nz-ca-chinook/config/chroms.tsv"


# Note, to disable sliding windows, I think you might just be able to
# define both fst_window_size and fst_window_step below to be
# empty lists: []


params:
  angsd_bam_filters: " -minMapQ 20  -minQ 33 -baq 1 "
  calc_saf: " -dosaf 1 -gl 1 "
  realSFS: " -fold 1 "
  winsfs: " "
  fst_window_size: [50000, 30000, 40000]
  fst_window_step: [10000, 5000,  20000]
  theta_window_size: [50000]
  theta_window_step: [10000]
  