bams: "example-configs/arg-nz-ca-chinook/config/bams_gv2.tsv"
pwcomps: "example-configs/arg-nz-ca-chinook/config/pwcomps.tsv"
#genome: "example-configs/arg-nz-ca-chinook/data/GCF_002872995.1_Otsh_v1.0_genomic.fna" 
genome: "example-configs/arg-nz-ca-chinook/data/GCF_018296145.1_Otsh_v2.0_genomic.fna" #make sure is the same reference genome that you used to run non-model and post-bcf pipelines

modes: ["BY_CHROM"]
chroms: "example-configs/arg-nz-ca-chinook/config/chroms_gv2.tsv"


# Note, to disable sliding windows, I think you might just be able to
# define both fst_window_size and fst_window_step below to be
# empty lists: []


params:
  angsd_bam_filters: " -minMapQ 20  -minQ 30 -baq 1 "
  calc_saf: " -dosaf 1 -gl 1 "
  realSFS: " -fold 1 "
  winsfs: " "
  fst_window_size: [50000, 30000, 40000]
  fst_window_step: [10000, 5000,  20000]
  theta_window_size: [50000]
  theta_window_step: [10000]
  